# pull official base image
FROM node:16.8.0-alpine as build

# set working directory
WORKDIR /front-sol

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /front-sol/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install --silent

# add app
COPY . ./

# build app
RUN npm run build
CMD ["npm", "start"]
