# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /front-sol

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /front-sol/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]
